select
    ORDER_ID, 
    USER_ID, 
    PROMO_ID, 
    ADDRESS_ID, 
    CREATED_AT::TIMESTAMPTZ AS CREATED_AT_UTC, 
    ORDER_COST, 
    SHIPPING_COST, 
    ORDER_TOTAL, 
    TRACKING_ID, 
    SHIPPING_SERVICE, 
    ESTIMATED_DELIVERY_AT::TIMESTAMPTZ AS ESTIMATED_DELIVERY_AT_UTC, 
    DELIVERED_AT::TIMESTAMPTZ AS DELIVERED_AT_UTC, 
    STATUS
from {{ source('postgres', 'orders') }}